## By NightAsylum: https://github.com/NightAsylum/Sysmon-Linux-Integration-For-Splunk
## MIT License
## Copyright (c) 2026 NightAsylum

[install]
is_configured = 0

[ui]
is_visible = 0
label = Sysmon Linux Integration For Splunk

[launcher]
author = NightAsylum
description = Sysmon Linux Integration For Splunk allows you integrate your sysmon linux setup with your Splunk. 
version = 1.0.0
