## By NightAsylum: https://github.com/NightAsylum/Sysmon-Linux-Integration-For-Splunk
## MIT License
## Copyright (c) 2026 NightAsylum

[eventtype=sysmon-linux-network]
network = enabled
communicate = enabled

[eventtype=sysmon-linux-process]
process = enabled
report = enabled

[eventtype=sysmon-linux-filemod]
endpoint = enabled
filesystem = enabled

[eventtype=sysmon-linux-service]
service = enabled
report = enabled
